<!-- ************ASSESSMENT SECTION**************************************** -->
#Assessment

<!-- ***********HISTORY AND CURRENT ASSESSMENT***************************** -->
##History Of Modeling Approaches Used For This Stock

Yellowtail rockfish was previously modeled as an age-structured, 3-area stock north of  $40^\circ 10^\prime$  in 1999 [@Tagart2000] using a model written in ADMB [@Fournier2012]; an update of this assessment was last conducted in 2004 [@Wallace2005].  That assessment divided the stock into 3 INPFC areas based on the suggestion that there might be biological differences in the stock, however recent genetic studies don't support that [@Hess2011].  The INPFC area boundaries are not coincident with state boundaries; this is a concern in that recent reconstructions of historical catch are state-by-state along the West Coast.  Because we cannot produce data that conform to the areas previously assessed, we have made no effort to reproduce the previous model.

A data-moderate approach was used to evaluate stock status in 2013 [@Cope2013].  The data-moderate model used only indices of abundance and made simplifying assumptions about selectivity and growth since no length or age data were included in the model.  This approach is also  incompatible with the current model, and we have made no attempt to reproduce it, either.

###Previous Assessment Recommendations

Many of the recommendations of the previous STAR panel are not relevant to this assessment, as they related to data deficiencies at that time that have since been resolved.  The 2004 STAR particularly recommended a focus on abundance indices, which they noted might require further survey information.

This assessment provides four indices for the Northern model, and three for the Southern model.  All indices are newly developed for this analysis.

\clearpage
\newpage


<!-- ************************MODEL DESCRIPTION***************************** -->

##Model Description


###Transition To The Current Stock Assessment
These are the main changes from the previous model, and our rationale for them:

1. Transition to Stock Synthesis. \emph{Rationale}: The Pacific Fishery Management Council's preferred modeling platform for stock assessments is Stock Synthesis [@Methot2015], developed since the last full assessment of yellowtail rockfish.

2. Addition of Southern model. \emph{Rationale}: Hess, et al. determined that the West Coast yellowtail stocks show a genetic cline occurring near Cape Mendocino, which is roughly  $40^\circ 10^\prime$ north latitude [@Hess2011].  This divides the stock into two genetically distinct substocks which we model independently.

2. Availability of recent data. \emph{Rationale}: Ten years of data collection have occurred since the last update assessment, and the data necessary for an assessment of the Southern stock is now available.

3. Historical catch reconstructions. \emph{Rationale}:  Reconstruction of catch timeseries in California, Washington and Oregon clarify stock history as far back as 1889.


###Definition of Fleets and Areas

The Northern model comprises the area between Cape Mendocino, California, and the Canadian border.  The Southern model runs from Cape Mendocino to the Mexican border (Figure \ref{fig:assess_region_map}).

**Northern Model** 

\emph{Commercial}: The commercial fleet consists primarily of bottom and midwater trawl.  No attempt was made to analyze the fishery separately by gear, particularly since it seems that in the fishery in the 1980s and 1990s, "bottom trawl" gear was used in the midwater as well as on the bottom, and "midwater gear" was sometimes dragged across soft bottom (Craig Goode, ODFW Port Sampler, pers. comm).

The data associated with the commercial fleet includes age- and length-composition data from PacFIN and CalCOM, historical catch timeseries from CDFW, ODFW and WDFW. Observations of discards from the Pikitch research study provide lengths and discard rates; discard lengths and rates calculated from WCGOP data.  Sex was available for the comps in the retained catch, which is by-sex in the model, but was not available for the discards, so they are undifferentiated by sex.

The PacFIN logbook (fish ticket) index developed for the commercial fishery is in fish/tow.  Further information about how the data for the index was worked up is in Appendix \ref{xxx}.

\emph{At-Sea Hake Fishery}: yellowtail rockfish are frequently caught in mid-water trawls associated with the At-Sea Hake Fishery (consisting of the Catcher-Processor and Mothership sectors). These catches are recorded and biological sampling takes place but the fish are processed at sea (typically into fish meal) and are not included in the PacFIN database, so this fishery requires separate analysis.  The At-Sea Hake fishery provides catches, length compositions by sex, and an index of abundance.

\emph{Recreational}: The recreational fleet includes data from sport fisheries off Oregon, and northern California (Eureka and Del Norte counties), from MRFSS and RecFIN.  The index of abundance for the recreational fleet is in fish per angler-hour.  Length data for this fleet are undifferentiated by sex.

\emph{Washington-Sport}:  The Washington data (WA_Sport) provides catches, lengths and ages, and was treated as a separate fleet for two reasons:  first, the length composition of the Washington catches were different from those in the recreational landings in Oregon and northern California (MRFSS/RecFIN data).  There are very large fish in this dataset, and fewer small ones.  Second, the WA_Sport landings are not available by weight, so they are entered in the model as numbers, andStock Synthesis internally converts them to weight using the combination of estimated selectivity for this fleet (informed by the length compositions), estimated growth, and the weight-length relationship.  Sex was available for the biological data, however many lengthed fish were not sexed, so the lengths for this fleet are undifferentiated by sex, although the ages are.

\emph{Research}:
The Alaska Fisheries Science Center's Triennial Trawl survey, provides age- and length-compositions, and an index of abundance.  This survey was conducted every third year from 1977-2004. Details on the workup of the CPUE (in biomass/area towed) can be found in Appendix \ref{xxx}.

The Northwest Fisheries Science Center's NWFSCcombo survey provides age- and length-compositions, as well as an index of abundance.  Details on the workup of the CPUE (in biomass/area towed) can be found in Appendix \ref{xxx}.


\emph{Conditional Age-at-Length}:  Only the NWFSCcombo ages were used as conditional age-at-length in the model.  All other aged fleets (Commercial, Washington\_Sport, and Triennial) are present in the model as marginal ages due to the amount of noise in the age data for those fleets.

\emph{Indices}:  Fish per angler-hour is the basis for the Washington\_Sport and Pikitch indices.  The NWFSCcombo and Triennial surveys provide indices based on biomass per area-towed.  The logbook survey for the commercial fleet is in units of fish per tow.

**Southern Model**

\emph{Commercial}: The commercial fleet consists primarily of hook and line and trawl gear.  Hook and line gear account for 78% of the landings by weight in the recent period (1978-2016).  Commercial data were sexed, although there are many unsexed lengths.  To preserve the large numbers of lengths, the length data are entered in the model as undifferentiated, however the ages are sexed and provide the sole conditional age-at-length timeseries in the Southern Model.

\emph{Recreational}: The recreational fleet includes data from sport fishery off the California coast south of Cape Mendocino.  The recreational lengths are unsexed.  The index is in fish per angler_hour.  Further information about how the index was worked up is in Appendix \ref{xxx}.

\emph{California Onbord Recreational Survey}: Research derived-data include observations from the California Onboard recreational survey.  The length-compositions from this survey are undifferentiated by sex.  The index is in fish per angler_hour.

\emph{NWFSC Hook-and-Line Survey}:  The data from this survey are used in the model as an index of fish per angler_hour, a single year of marginal age data by sex, and sexed length compositions.

\emph{Small Fish Study}: A separate index, length comps and a single year of ages reflect a small study of juvenile fish conducted by the SWFSC.


###Modeling Software
The STAT team used Stock Synthesis 3 [@Methot2015], which is the Pacific Fishery Management Council's preferred modeling platform for assessments.

###Data Weighting

Commercial and survey length composition and marginal age composition data are weighted according to the method of Ian Stewart (pers.comm):

   Sample Size = 0.138 * Nfish + Ntows if Nfish/Ntows < 44, and Ntows * 7.06 otherwise.

Age-at-Length samples are unwieghted; that is, each fish is assumed to represent an independent sample.

Recreational trips (the analogue of tows in the commercial fishery) are difficult to define in most cases.  Since much of the recreational data are from the dockside interview MRFSS program, which didn't anticipate the need to delineate samples as belonging to particular trips, we chose to use all recreational data "as-is", with the initial weights entered as number of fish.

Weighting among fleets uses either the Francis method [@Francis2011] or the Ianelli-McAllister harmonic mean method [@McAllister1997].  The Francis method was used for all fleets, except for the age data from the Southern model's Hook and Line survey, which is a single year of data to which we applied the Ianelli-McAllister method.


###Priors \label{priors}


Hamel [-@Hamel2015] developed a method for combining meta-analytic approaches to relating the natural mortality rate M to other life-history parameters such as longevity, size, growth rate and reproductive effort, to provide a prior on M. In that same issue of ICESJMS, Then et al. [-@Then2015], provided an updated data set of estimates of M and related life history parameters across a large number of fish species, from which to develop an M estimator for fish species in general.
They concluded by recommending M estimates be based on maximum age alone, based on an updated Hoenig non-linear least squares estimator $M=4.899A_{max }^{-.916}$. 

The approach of basing M priors on maximum age alone was one that was already being used for west coast rockfish assessments. However, in fitting the alternative model forms relating M to Amax, Then et al. did not consistently apply their transformation. In particular, in real space, one would expect substantial heteroscedasticity in both the observation and process error associated with the observed relationship of M to Amax. Therefore, it would be reasonable to fit all models under a log transformation. This was not done.

Re-evaluating the data used in Then et al. [-@Then2015] by fitting the one-parameter Amax model under a log-log transformation (such that the slope is forced to be -1 in the transformed space (as in @Hamel2015), the point estimate for M is $M=5.4/Amax$

This is also the median of the prior. The prior is defined as a lognormal with mean lna(5.4/Amax) and SE = 0.4384343. 

Natural mortality priors for these models were based on examination of the 99\% quantile of the observed ages from early in the time-series, before the full impact of fishing would have taken place. For the Northern model, these quantiles were approximately 35 years for females and 45 years for males, resulting in median M values of 0.15 and 0.12 for females and males. For the Southern model, the 99\% quantile of the early age observations were approximately 30 and 40 years for females and males, resulting in median M prior values of 0.18 and 0.135, respectively. In both models, M for males was represented as an offset from females. In the Northern model, both the female value and the male offset could be estimated without priors so the priors were not used. For the southern model, M was fixed at the median prior values for the two sexes.

The prior for steepness ($h$) assumes a beta distribution with parameters based on an update of the Thorson-Dorn rockfish prior (commonly used in past West Coast rockfish assessments) conducted by James Thorson (personal communication, NWFSC, NOAA) which was reviewed and endorsed by the Scientific and Statistical Committee in 2017. The prior is a beta distribution with $\mu$=0.718 and $\sigma$=0.158.


###General Model Specifications
Fecundity is represented in the models as:  $1.1185^{-11}W^{4.59}$.  This is a rescaling of the values provided in [@Dick2017].

Model data, control, starter, and forecast files can be found at \hl{https://DEVORE}


###Estimated And Fixed Parameters
A full list of all estimated and fixed parameters is provided in Tables....
Estimated and fixed parameters tables currently read in from .csv file, 
EXAMPLE: Table \ref{tab:Model1_params}


**Growth**
5 parameters for female growth are estimated in each model: 3 von Bertalanffy parameters and 2 parameters for CV as a function of length at age  related to variability in length at age for small and large fish.

Three parameters are estimated for male growth in each model as offset from female growth.  The size for small fish and CV for small fish were assumed equal to females.

**Natural Mortality**
Natural mortality is estimated in the Northern model with an offset for males from females.  Natural Mortality is fixed in the Southern model at the values provided by the Hamel [-@Hamel2015] analysis described above.

**Selectivity**
Selectivity for all fleets was initially estimated as a 4-parameter double normal, which allows selectivity to be dome shaped, with parameters controlling the position of the peak selectivity, the width of the peak, and the ascending and descending slopes. 

For all fleets where the estimated patterns were asymptotic, we fixed the parameters related to the dome, leaving only the position of the peak and the ascending slope as estimated parameters. For a few fleets, the position of the peak hit the upper bound, and was fixed at 55cm.

**Retention**
Retention for commercial fishery in Northern model is a logistic function of size, with three parameters estimated: length at 50% retention, the slope of the curve, and the asymptotic retention fraction. The asymptote was allowed to be time-varying, with one value applied for the early years through 2001.  From 2002 through 2011 we applied annual time-blocks for theses years when the WCGOP program observed high discards.  The final block runs from 2012 forward, reflecting the current period in which the implementation of the IFQ program has led to low discard rates.

**Other Estimated Parameters**
Log(R0) is the equilibrium recruitment, which is estimated in each model.  

Recruitment deviations for the Northern model are estimated from 19xx to 2013.  For the Southern model recruitment deviations are estimated from 19xx to 2013.  \hl{list range of years for each model with some comment as to how this range was chosen}. 

A parameter for extra standard deviation was added to the index based on bycatch in the at-sea hake fishery,  because this index was not well fit by any of the models considered.

\clearpage

##Model Selection and Evaluation
###Key Assumptions and Structural Choices
Selectivity in both models is asymptotic, with the exception of the OR-CA MRFSS recreational fleet in the Northern model, and the Onboard recreational fleet in the Southern model.

For the Northern model, several options for developing a CPUE series for the recreational fishery were considered but rejected as sparse and noisy.  Similarly, the Washington\_Sport fishery data was evaluated a a possible source for an index, but the data was not available in a form useful for a recreational index, i.e., there was no data that provided for a trip-level analysis of catch and effort, as was used for the MRFSS index in the Southern model [@Stephens2004].

###Alternate Models Considered
Time-blocked selectivity and retention were investigated in the Northern model, as were domed selectivities.

We also explored time-blocks on selectivity in the Southern model, and domed selectivity for the MRFSS/RecFIN data.

These approaches resulted in model fits to data that were obviously poor, and so they were rejected

###Convergence
Convergence testing through use of dispersed starting values often requires extreme values to explore new areas of the multivariate likelihood surface. Stock Synthesis provides a jitter option that generates random starting values from a normal distribution logistically transformed into each parameter's range [@Methot2015]. We used this function to find parameter values for convergence in the Southern model.  The Northern model \hl{report jittering when it's been done}.

\clearpage

##Response To The Current STAR Panel Requests
\begin{description}[style=unboxed]

\item[Request No. 1: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.  

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 2: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 3: Add after STAR panel.] \hfill \\

    \textbf{Rationale:} Add after STAR panel.
  
    \textbf{STAT Response:} Add after STAR panel.

\item[Request No. 4: Example of a request that may have a list:] \hfill \\
\begin{itemize}
\item \textbf{Item No. 1}
\item \textbf{Item No. 2}
\item \textbf{Item No. 3, etc.}
\end{itemize}

    \textbf{Rationale:} Add after STAR panel.

    \textbf{STAT Response:} Continue requests as needed.


\end{description}

\clearpage

<!-- *********************MODEL 1 RESULTS********************************** -->

## Life History Results for both models

Maturity in the model was estimated outside the model at the Northwest Fisheries Science Center by Melissa Head, and is shown in Figure \ref{fig:maturity}.

Figure \ref{fig:weight-length} shows the results of the analysis of the Weight-Length relationship estimated and used as fixed input for both models.

The growth at the beginning of the year estimated by the models for the Northern and Southern stocks is shown in Figure \ref{fig:growth}.  Females grow faster in each case, but the Northern stock grows faster and attains larger maximum size.

## Northern Model Base Case Results

The data used in the Northern model by fishery is shown in Figure \ref{fig:data_plot.N}.  Estimated catches are shown in Figure \ref{fig:r4ss_total_catch_N}; estimated discards are in Figure \ref{fig:r4ss_discard_N}.  These show the large catches in the 1980s and 90s are being predicted by the model.  The large discards in latter years match the data well for those years.

The timeseries of estimated spawning output in trillions of eggs is shown in Figure \ref{fig:ssb.N}.  The model is estimating two periods of decline, one beginning in the forties and a steeper decline in the 1970s and 1980s, followed by an increase since 2000 to pre-1980 levels. There is a decrease in the final years of the timeseries coincident with increased uncertainty.


Figure \ref{fig:total_bio.N} shows the total biomass following a similar pattern; the ending value is `r round(mod1$timeseries$Bio_all[mod1$timeseries$Yr==2017])` metric tonnes.

The relative spawning output (Figure \ref{fig:depl.N}) went below the 40\% target in the early 1980s, and may have been below the minimum stock size limit of 25% in the late 1990s, but has rebounded since to `r round(100*mod1$derived_quants["Bratio_2017","Value"])`% (see Table \ref{tab:Timeseries_mod1}).

Figures \ref{fig:recruits1.N} and \ref{fig:recdevs1.N} address recruitments estimated the the model.  The first of these shows the age-0 recruits, and the second the recruitment deviations. There are no strong patterns in recruitment and the variability of the recruitment deviations was tuned to be 0.546 (based on the method of Methot & Taylor @Methot2011) which is slightly lower than what has been assumed or estimated for other rockfish in the California Current.  The stock-recruit curve, Figure \ref{fig:stock_recruit_curve.N} shows a shallow relationship between stock size and recruitment.}



### Selectivities, Indices and Discards

Selectivities in the Northern model (Figure \ref{fig:selex.N}) shows the difference between the recreational fisheries and the commercial fishery and survey sampling.  All of the fish are fully selected by 50 cm, but the recreational fish are fully selected at 30 cm.

Retention by length (Figure \ref{fig:retention.N}) varies over time between 40\% and 100\%, with no clear pattern of interannual variation, except for the trawl-rationalization era 2011-present.

Discarding in the commercial fleet (Figure \ref{fig:r4ss_discard_fits.N}) is fit only by putting blocks on retention in the Northern model.  Discards were very low except during the 1990s and 2000s, until the trawl-rationalization program implementation.

Fits to the indices for the northern model (Figure \ref{fig:index_fits1}) demonstrate the utility of the NWFSCcombo survey.  Although the model misses the uptick at the end of the timeseries, it is the only recent index and is well-fit by the model.  The other indices are noisier.  Most of the indices are fairly flat, indicating little change in abundance during each time-period.  Although the fit to the Triennial index is poor, the data nicely reflects the changes in management during it's tenure:  the CPUE was falling during the 1980s and 1990s, then rising after stringent restrictions began in 2000.

### Lengths
Bubble plots for the lengths in the fishery (Figure \ref{fig:comp_length_bubble_mod1_page1}) show the constancy of the commercial fleet, and the differences in growth between males and females; the females are larger, the males smaller.  The recreational fleet is represented by two different sampling regimes, and the changeover in the mid-2000s is clear in that panel.  That the WA\_Sport fishery catches larger fish is represented in the large bubbles at the top of the panel.  Had we examined that fishery earlier in the process of putting the model together, we might have settled on a larger maximum size bin, however that fishery remains the smallest portion of the catches.

Commercial length comps are very well fit (Figures \ref{fig:mod1_1_comp_lenfit_flt1mkt2_page1} and \ref{fig:mod1_5_comp_lenfit_data_weighting_TA1.8_Commercial Fishery}).  Commercial discards are noiser and not well fit (Figure \ref{fig:mod1_6_comp_lenfit_flt1mkt1}) although the fit to the mean length (which is lower than for the retained fish), is reasonable (Figure \ref{fig:mod1_5_comp_lenfit_data_weighting_TA1.8_Commercial Fishery}). 

Lengths in the early period of the Hake Bycatch fishery are noisy (doubtless due to small sample sizes).  By 1992, the model is able to fit the data well (Figures \ref{fig:mod1_10_comp_lenfit_flt2mkt0} and \ref{fig:mod1_13_comp_lenfit_data_weighting_TA1.8_At-Sea Hake Fishery}).

The recreation OR+N.CA timeseries of lengths demonstrates the difference between the MRFSS sampling and RecFIN sampling.  The fits in the early period are good, those in the later period are noisy and model uncertainty is high (Figures \ref{fig:mod1_14_comp_lenfit_flt3mkt2} and \ref{fig:mod1_17_comp_lenfit_data_weighting_TA1.8_Recreational OR+CA}).

The WA_Sport length fits might have been improved with a better choice of maximum size bin for the model (Figures \ref{fig:mod1_18_comp_lenfit_flt4mkt2} and \ref{fig:mod1_21_comp_lenfit_data_weighting_TA1.8_Recreational WA}), however the data are noisy throughout the size range represented.

The Triennial lengths Figures \ref{fig:mod1_22_comp_lenfit_flt5mkt2} and \ref{fig:mod1_25_comp_lenfit_data_weighting_TA1.8_Triennial Survey} are fit well in some years and not in others.  The data is not noisy, however the intermittency of data collection may mean that the model is unable to capture interannual variation as well as for an annual timeseries.

NWFSCcombo lengths are not well fit, particularly in 2013, where the data show a large number of small fish that may represent a good recruitment several years earlier Figures \ref{fig:mod1_26_comp_lenfit_flt6mkt2} and  \ref{fig:mod1_29_comp_lenfit_data_weighting_TA1.8_NWFSC Combo Survey}.

Figure \ref{fig:mod1_30_comp_lenfit__aggregated_across_time} shows the relative fits among the data sources, aggregated across time.  The timeseries of presence-absence residuals indicated by filled- and open-bubbles Figure \ref{fig:comp_Pearson_length_mod1_page1} and Figure \ref{fig:comp_Pearson_length_mod1_page2} demonstrates the relative disappointment in model fits; the smaller the bubble, the better the match between the data and the model expectation.

### Ages

The NWFSCcombo survey provided the only source of conditional age-at-length data for the Northern model; ages for other fleets were treated as marginal ages.  

The fits to the marginal commercial Figure \ref{fig:mod1_1_comp_agefit_flt1mkt2_page1} are quite good from about 1979 on, even fitting the tail where the ages beyond 55 are lumped.  The weightings panel Figure \ref{fig:mod1_5_comp_agefit_data_weighting_TA1.8_Commercial Fishery} shows the same thing:  fits are good after about 1979, and the decrease in mean age in the population corresponds with high catches in the 1980s and 1990s, with mean age increasing after 2000 as catches were curtailed.

The Washington Sport ages are noisy, and the fit is poor throughout the timeseries, see Figure  \ref{fig:mod1_6_comp_agefit_flt4mkt2} and Figure \ref{fig:mod1_9_comp_agefit_data_weighting_TA1.8_Recreational WA}.

The Triennial ages are noisy but are fit surprisingly well \ref{fig:mod1_10_comp_agefit_flt5mkt2}; \ref{fig:mod1_13_comp_agefit_data_weighting_TA1.8_Triennial Survey}.  That the model misses the influx of young fish in 1986 may be due to the timing of the survey; three-year surveys may not provide enough data for the model to fit recruitment events. 

Aggregated age comps for the Commercial, Washington Sport and Triennial fleets are shown in Figure  \ref{fig:mod1_14_comp_agefit__aggregated_across_time}, for comparison.  Agreggated fits for the Commercial and Triennial fleets are very satisfying.

The implied marginal age comps for the NWFSCcombo survey (Figure \ref{fig:mod1_16_comp_gstagefit_flt6mkt2}) are the conditional-age-at-length compositions for the survey aggregated over length.  This figure is included for informational purposes only; the marginal "ghost" comps are not included in the likelihood calculations.  It is interesting that the model fits these implied marginal ages less well than the conditional ages at length. This is likely due to a combination of factors: the implied marginal ages are not included in the liklihood, and when anomolous patterns appear, such as the numerous age-5 fish in 2013, as long as their ages are as expected given their lengths, the conditional-age-at-length data will be well fit. The implied marginal ages are also expanded to account for the size of the sampled catch relative to the total catch while the conditional data are not.

Pearson residuals for the marginal age comps, are shown in the bubble plots in Figure \ref{fig:comp_Pearson_age_mod1}.  The filled bubbles represent estimates greater than observations, and the open bubbles observations greater than estimates. The large filled bubbles at age 25 in a few years suggest that we might have chosen a slightly older age as the compilation age.

The residuals for the conditional age-at-length from the NWFSCcombo survey show that growth appears to be reasonably estimated with no strong patterns suggesting consistently older or younger fish than expected in any year (Figure \ref{fig:mod1_1_comp_condAALfit_residsflt6mkt2_page1}). However, the mean age aggregated across length bins shows more variability in the observations than expected by the model (Figure \ref{fig:mod1_3_comp_condAALfit_data_weighting_TA1.8_condAgeNWFSC Combo Survey}).  This may represent young fish recruiting to the fishery, which would happen approximately 5 years after a biological recruitment event.  The conditional age-at-length fits are also shown in Figure \ref{fig:mod1_3_comp_condAALfit_data_weighting_TA1.8_condAgeNWFSC Combo Survey}.  These plots explain the reason this survey was chosen to represent conditional age-at-length; the model was able to fit these data much better than other datasets, and improved fit, lower likelihood values and increased parsimony all contributed to a better model.

## Northern Model Parameters
For the Base model, the parameter estimates are given in Table \ref{tab:Model1_params}.  Status for all of the estimated parameters is good, with the exception of the 6th parameter for the selectivity in the Washington Sport fishery.   

### \hl{Northern Model Uncertainty and Sensitivity Analyses}
Table \ref{tab:Sensitivity_model1}


### Northern Model Retrospective Analysis
 

### Northern Model Likelihood Profiles
We profiled the change in negative log likelihood for the data sources and model total likelihood for critical parameters in the model:  **R0**, the log of equilibrium recruitment; female natural mortality, **MF**; male natural mortality, **MM**; and steepness, **h**, the parameter that reflects how quickly the stock-recruit relationship allows the stock to rebound from depleted stock size.

The likelihood profile over a range of values (from 9 to 11) R0 are shown in Figure \ref{fig:profile_logR0.N}.  This plot shows the tension between the index data and the other data sources.  The indices are better fit with a smaller value of R0, near 9.6, while all other data sources are better fit at larger values.  The overall likelihood in the model is lowest at 10.3 in this figure.  The discards show very little change (are insensitive) over this range of R0, while the recruitments, ages and lengths are all minimized at values larger than 10.5.

The likelihood profile over female natural mortality, MF, is over a range from 0.1 to 0.24 (Figure \ref{fig:profile_M.N}).  In this figure, the indices are fit best when MF is 0.1, the ages and lengths are fit nearer 0.18, and the recruitments and total log likelihoods are minimized at 0.15.


Figure \ref{fig:profile_M2.N} shows the likelihood profile for male natural mortality, MM, over a range of negative values that are the offset from female mortality (FM).  The index data are again at odds with the other data sources; all but the indices are minimized at a value of -0.15.  Male natural mortality is represented as an offset from that for females based on the equation $MM = MF*exp(offset)$, such that an offset of 0 results in equal mortality for males and females, and an offset of -0.3 results in a male natural mortality which is about 74% of the female mortality ($exp(-0.3) = 0.7408$).


The profile over values of steepness, h, from 0.5 to 0.9, Figure \ref{fig:profile_h.N}, shows the index data for once in the majority as all data sources except the lengths support 0.9 as minimizing the likelihood, while the lengths support a value closer to 0.5.  The scale of this plot differs from the others; it is roughly a tenth of the scale of the R0 plot, meaning that the choice of h within this range has far less impact on likelihood in the model than choices for the other profiled parameters.  This suggests the stock is not depleted; the choice of steepness would have a much greater impact on a depleted stock.


### Northern Model Reference Points

Intro sentence or two....(Table \ref{tab:Timeseries_mod1}). 

Equilibrium yield at the proxy $F_{MSY}$ harvest rate corresponding to 
$SPR_{50\%}$ is 


\hl{Knit kept whining about missing ref pts table, wouldn't work, took out ref.}

shows the full suite of estimated reference points for the northern area model 
and Figure \ref{fig:Yield_all} shows the equilibrium yield curve.


\clearpage

<!-- *************************MODEL 2 RESULTS****************************** -->

## Southern Model Base Case Results

Data used in the Southern model is shown in Figure \ref{fig:data_plot.S}. 

One thing to point out is that although the scale of the biomass in the model is somewhat sensitive to various data sources, the depletion is not.  In tuning the model we were suprised to note that depletion always stayed above 80\%.

Estimated catches are shown in Figure \ref{fig:r4ss_catch2_S}.

The estimated spawning biomass in Figure \ref{fig:ssb.S} shows the size of the uncertainty in this model. Total biomass (Figure \ref{fig:total_bio.S}) shows a sharp upward trend in recent years, the decade with only one year of age data from the Hook-and-Line Survey.  Spawning depletion has sinuous curves and was likely never as low as the 40% target, even in the 1980s-1990s (Figure \ref{fig:depl.S}.

Recruitments have been constant, except 2008 and 2010, when the model sees extra large recruitments with extra large recruitment deviations (Figures \ref{fig:recruits1.S} and \ref{fig:recdevs1.S}).  The spawner-recruit curve, Figure \ref{fig:stock_recruit_curve.S} is a line.

### Southern Model Selectivities, Indices and Discards

Selectivity by fleet is shown in Figure \ref{fig:selex.S}.  Selectivities for all but the recreational Onboard fishery are modeled as asymptotic; both recreational fleets (MRFSS/RecFIN and Onboard) are fully selected at 30cm; the remaining fleets show full selectivity at 45-50 cm.

Index fits leave something to be desired.  All are more-or-less flat, with all of the three current indices, the Onboard, the Juvenile study and the Hook-and-Line survey all missing a downturn at the end of the timeseries.  During model tuning, we tried introducing a time-blocked index for the two periods of the Onboard survey, however it didn't improve the fit to the index significantly, and increased the (negative log) likelihood of the model.

There was little information to inform the Southern Model of discard behavior, except in the Onboard survey, where it was represented by extremely small numbers.  We included these discards in the retained fishery, since attempts to include it as a type-1 "retained plus discards" fishery prevented the model from converging.

### Southern Model Lengths
Lengths in the Southern model were entered as unsexed, except for the Hook-and-Line fishery.  There were sexes for the Commercial lengths, however there were also large numbers of unsexed lengths, and we chose to model the lengths as unsexed, to include as much of the data as possible.  This was true of the Small-Fish study, as well.

Bubble plots of the lengths by year in each fishery are in Figure \ref{fig:comp_length_bubble_mod2}.  The plot for the recreational fishery clearly shows the transition from the MRFSS sampling program to RecFIN in 2003/2004, as well as suggesting the existence of larger fish in the 1980s.  The Commercial fishery data has been sparse in recent years, however the fish taken in the Commercial catch are consistently larger than those in the recreational fishery, no doubt reflecting trawling in deeper waters.  The Onboard survey lengths reflect two eras of sampling, again with larger fish in the earlier period.  The panel for the Hook-and-Line survey shows that the females landed are always larger than the males, in agreement with the model estimates of growth: Figure \ref{fig:growth}.

The fits to the lengths in the Recreational fishery Figure \ref{fig:mod2_1_comp_lenfit_flt1mkt2} show variable fits through the years, with the noisy and sparse data in 2004 heralding the transition between MRFSS sampling and RecFIN.  Overall, the timeseries is fit fairly well: Figure \ref{fig:mod2_4_comp_agefit_data_weighting_TA1.8_Recreational Onboard Survey}

The Commercial length comps are fit well through 2005, when data becomes sparse and noisy Figure \ref{fig:mod2_5_comp_lenfit_flt2mkt2}; and Figure \ref{fig:mod2_8_comp_lenfit_data_weighting_TA1.8_Commercial Fishery}.

Fits for the Onboard Survey lengths are good in the early survey, and poor for the later period \ref{fig:mod2_9_comp_lenfit_flt3mkt2}; \ref{fig:mod2_12_comp_lenfit_data_weighting_TA1.8_Recreational Onboard Survey}.  Attempting to apply a time-block to this data resulted in poor convergence.

The Hook-and-Line Survey lengths are noisy (Figure \ref{fig:mod2_13_comp_lenfit_flt4mkt0}), but the fits are acceptable, and follow the trend of the data better than those for the other datasets:  Figure \ref{fig:mod2_16_comp_lenfit_data_weighting_TA1.8_Hook & Line Survey}.

The small fish survey lengths are not fit badly \ref{fig:mod2_17_comp_lenfit_flt5mkt2}; \ref{fig:mod2_20_comp_lenfit_data_weighting_TA1.8_Recreational Study}, and it is perhaps a shame that there are so few years to this timeseries.

The aggregate fits to the length comps for all five datasets is shown in Figure \ref{fig:mod2_21_comp_lenfit__aggregated_across_time}, and Pearson residuals for the lengths in Figure \ref{fig:comp_Pearson_length_mod2}.  Filled bubbles represent under-estimation of the data, open bubbles represent overestimation.


### Southern Model Ages
There are few marginal ages in the model.  Bubble plots for the Southern model ages (Figure \ref{fig:comp_age_bubble_mod2}) show the small sample from the Juvenile Fish Study and the single year of ages from the Hook-and-Line Survey.  The samples are too small to show any inter-annual variation, and are noisy within-year.

Figure \ref{fig:mod2_1_comp_agefits} shows the fit to the Recreational Fishery samples, which is poor in all four years.  The mean age in this data is shown in Figure \ref{fig:mod2_4_comp_agefit_data_weighting_TA1.8_Recreational}, at 10 years.

The Hook-and-Line Survey age "fit" is shown in Figure \ref{fig:mod2_5_comp_agefit_flt4mkt0}.  The Francis tuning method could not be applied in this case as it depends on the fit to multiple years of data.

The aggregated fits for the marginal, and I *do* mean *marginal* ages are shown in Figure \ref{fig:mod2_9_comp_agefit__aggregated_across_time}.  They speak for themselves.

The implied marginal age distribution from the commercial conditional-age-at-length compositions is shown in Figure \ref{fig:mod2_11_comp_ghost}.  This figure is included for informational purposes only; as it does not contribute to the model likelihood calculations.  The fits here are quite good 1981-1999, however the last three years of data are very sparse and not well fit.

Pearson residuals for the Small Fish Juvenile Study and the Hook-and-Line Survey are shown in Figure \ref{fig:comp_Pearson_age_mod2}.  Bubble size indicates the amount of disappointment in the fits.  The filled bubbles indicate underestimates by the model; the open bubbles indicate overestimates.

The good news age-data comes from the commercial fleet, as was foreshadowed by the implied marginal ages.  Figure \ref{fig:mod2_4_comp_condAALfit_data_weighting_TA1.8_condAgeCommercial} shows the interannual fits to the mean age in the commercial age-at-length data.  Except for 1981, 1982 and 1989, the model is able to fit the data reasonably well, detecting the downward trend in the late 1980s and into the mid-1990s.

The annual plots of age-at-length fits (Figure \ref{fig:mod2_5_comp_condAALfit_Andre_plotsflt2mkt2_page1}) show good fits in all years except 2001-2002.


### Southern Model Uncertainty and Sensitivity Analyses

The Southern model was investigated in these N ways:
\begin{description}
\item[EarlyCatch] Because the fishery began in the 1880s, we used a linear ramp from 0 catch in 1898 (the first year in the Northern model) to the first catch in 1928 for the commercial fleet.
\item[NoSmall] The small fish study was included to provide information about growth of young fish.  We took out the biological data associated with this study.
\item The NWFSCcombo data for south of Cape Mendocino is sparse.  We added it to the model to investigate its utility.
\item[AddIndex] The index for the NWFSCcombo survey south of Cape Mendocino was also added to the Southern model.
\item[M Prior] Turn on the prior for M and see if the model can estimate it.  M has been a fixed parameter since very early runs of the model, but changes since then may have made M estimable.
\item[Age64] The literature value for maximum age is 64.  We fixed mortality at 0.0844, the value associated with that age, to investigate its effect on the model.
\item[NorthMs] We also investigate the effect of using the natural mortalities for males and females estimated by the Northern model.
\item[SplitIndices] We split the recreational indices (MRFSS and Onboard) into two separate timeseries, since the model had trouble fitting these indices.
\item[NoIndex X]We turned off each index in turn (MRFSS, Onboard, Juvenile Study and the Hook-and-Line Survey).
\end{description}

Results of these investigations can be seen in Figure \ref{xxx}, and Table \ref{yyy}.

### Southern Model Retrospective Analysis

### Southern Model Likelihood Profiles
We profiled the change in negative log likelihood for the data sources and model total likelihood for critical parameters fixed in the model:  **R0**, the log of equilibrium recruitment; female natural mortality, **MF**; male natural mortality, **MM**; and steepness, **h** the parameter that reflects how quickly the stock-recruit relationship allows the stock to rebound from depleted stock size.

The likelihood profile for **R0** is shown in Figure \ref{fig:profile_logR0.S}.  R0 was profiled over values from 8.5 -11.  The figure shows that the age data and indices are minimized when R0 is 11; the length data are minimized around 8.5, and the recruitments at 9.8 (or so).  The overall likelihood is minimized near 10.5.

The female natural mortality (FM) profile, \ref{fig:profile_M.S} ranges from 0.1 to 0.24.  The age and length data sources are at odds over FM; the ages and recruitments are minimized when FM is the low end of the range, and the lengths and indices when it is highest.  Changes to the recruitment likelihood is minimal over the whole range.  The overall likelihood is minimized near 0.22.

Male natural mortality (MM) is profiled over a range from -0.4 to 0.  Male natural mortality is represented as an offset from that for females based on the equation $MM = MF*exp(offset)$, such that an offset of 0 results in equal mortality for males and females, and an offset of -0.3 results in a male natural mortality which is about 74% of the female mortality ($exp(-0.3) = 0.7408$).  All roads lead to Rome in this figure (Figure \ref{fig:profile_M2.S}); since all data sources and the overall likelihood are minimized at zero.  Likelihoods for recruitments and indices are flat over the range of MM; the other data sources show changes of 20 (lengths) and 80 (ages) likelihood values.

The steepness profile (Figure \ref{fig:profile_h.S}is the most colorful, as the lines bounce around and change direction, however the likelihood scale is from 0 to 0.7, meaning that none of the values in this range (0.5 - 0.9) would have much impact on likelihood in the model.  This supports the conclusion that the stock is abundant.  For a depleted stock, steepness would have a very large impact on the likelihood.


### Southern Model Reference Points

## Comparison of the Northern and Southern Model Results.

\hl{No text yet}

